exports.statusCodes = {
  success: 200,
  created: 201,
  noContent: 204,
  badRequest: 400,
  unauthorized: 401,
  forbidden: 402,
  notFound: 404,
  conflict: 409,
  unproccessible: 422,
  methodsNotAllowed: 405,
  lengthRequired: 411,
  uriTooLarge: 414,
  unsupportedMediaType: 415,
  internalServerError: 500,
  notImplemented: 501,
  badGateway: 502,
  serviceUnavailable: 503,
  gatewayTimeout: 504,
};

exports.roles = {
  admin: "ADMIN",
  user: "USER",
};
exports.errors = {
  invalidPhoneNumber: "Invalid phone number!",
  somethingSeemsWrong: "Oops! something seems wrong.",
  somethingWentWrong: "Oops! something went wrong.",
};
exports.messages = {
  countrySaved: "Country added successfully!",
  countryNotSaved: "Country couldn't save!",
  countryAlreadyExists: "Country already exists!",
  countryNotExists: "Country does not exists!",
  countryExistsByCode: "Country code already exists! Please check the details.",
  userCreated: "User created successfully!",
  userNotCreated: "User couldn't create!",
  userAlreadyExists: "User already exists!",
  userNotExists: "User not exists!",
  userUpdated: "User details updated successfully!",
  userNotUpdated: "User couldn't update!",
  phoneNumberNeedToBeUpdated:
    "Phone need to be updated while updating the country",
  adminNotExists: "Admin not exists!",
  adminCreated: "Admin created successfully!",
  adminNotCreated: "Admin could not create!",
  adminAlreadyExists: "Admin already exists!",
  adminNotExists: "Admin not exists!",
  adminUpdated: "Admin details updated successfully!",
  adminNotUpdated: "Admin couldn't update!",
  nothingUpdated: "Nothing to update!",
  countryHasNoServiceAvailable:
    "Currently, service is not available in this country!",
  allUsersFetched: "All the users details fetched successfully!",
  userFetched: "User details fetched successfully!",
  adminFetched: "Admin details fetched successfully!",
  invalidUserId: "Please provide the valid User id!",
  invalidAdminId: "Please provide the valid Admin id!",
  countriesFetched: "All the countries fetched successfully!",
  countryFetched: "Country details fetched successfully!",
  invalidCountryId: "Please provide the valid Country id!",
  countryStatusRequired: "Please provide the country status!",
  invalidCountryStatus:
    "Please provide the valid status value! only boolean value allowed.",
  countryNotUpdated: "Country couldn't update!",
  emailMissing: "Email is required!",
  passwordMissing: "Password is required!",
  countryCodeRequired: "Country code is required!",
  countryCodeEmpty: "Country code should not be empty!",
  countrySlugRequired: "Country slug is required!",
  countrySlugEmpty: "Country slug should not be empty!",
  emailEmpty: "Email should not be empty!",
  passwordEmpty: "Password should not be empty!",
  wrongCredentials: "Wrong credentials!",
  refreshAuthTokenNotGenerated: "Oops! Refresh auth token couldn't generate!",
  sessionCouldNotSaved: "Oops! Session couldn't save to database!",
  accessTokenNotGenerated: "Oops! access token couldn't generate!",
  authenticated: "Authenticated successfully!",
  accountDisabled:
    "Sorry! your account is disabled. Please contact to the administrator.",
  productCreated: "Product created successfully!",
  productNotCreated: "Product couldn't created!",
  productAlreadyCreated: "Product already created!",
  authorizationTokenRequired: "Please provide the authorization token.",
  invalidAuthorizationToken: "Invalid authorization token.",
};
